apiVersion: v1
kind: Service
metadata:
  #creationTimestamp: 2019-01-04T09:44:40Z
  labels:
    app: exporter-kube-etcd
    chart: exporter-kube-etcd-0.1.15
    component: kube-etcd
    heritage: Tiller
    release: kube-prometheus
  name: kube-etcd
  namespace: kube-system
  resourceVersion: "30253833"
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 2222
    protocol: TCP
    targetPort: 2222
  sessionAffinity: None
  type: ClusterIP
