apiVersion: v1
kind: Service
metadata:
  labels:
    app: exporter-kube-dns
    chart: exporter-kube-dns-0.1.7
    component: kube-dns
    heritage: Tiller
    release: kube-prometheus
  name: kube-dns
  namespace: kube-system
  resourceVersion: "30253832"
spec:
  clusterIP: None
  ports:
  - name: http-metrics-dnsmasq
    port: 10054
    protocol: TCP
    targetPort: 10054
  - name: http-metrics-skydns
    port: 10055
    protocol: TCP
    targetPort: 10055
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
