apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  clusterName: ""
  labels:
    app: exporter-kube-dns
    chart: exporter-kube-dns-0.1.7
    component: kube-dns
    heritage: Tiller
    prometheus: kube-prometheus
    release: kube-prometheus
  name: kube-dns
  namespace: monitoring
  resourceVersion: "30253918"
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics-dnsmasq
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics-skydns
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: exporter-kube-dns
      component: kube-dns
